all: demo

readFile.o: readFile.c
	gcc -c -g readFile.c -o readFile.o
aes256.o: aes256.c aes256.h
	gcc aes256.c -g -ggdb -c -o aes256.o
demo.o: demo.c
	gcc demo.c -ggdb -c -g -o demo.o
tryCombs.o: aes256.o tryCombs.asm
	nasm tryCombs.asm -g -F dwarf -f elf32 -o tryCombs.o
demo: demo.o aes256.o tryCombs.o readFile.o
	gcc -g -ggdb demo.o aes256.o tryCombs.o readFile.o -o demo
clean:
	rm *.o
